### PR TITLE
ch03 ch04

### PR DESCRIPTION
**Pull request by iwatobipen**
Hi, I tried ch03 translation. Any comments and suggestions are highly appreciated.

### CODE REVIEW

**Comment by kzfm** [comment]
I don't think it is a good way to introduce Japanese sites like Qiita in the English version

**Comment by iwatobipen** [comment]
Thanks for your comment. That makes sense. I will change the part.

**Comment by iwatobipen** [comment]
Do I need change URL links where link Japanese books and sites?
Some reference books are written in Japanese only.

**Comment by iwatobipen** [comment]
Tried ch04 translation

**Pull request merged**
